# Generated by Django 5.2 on 2025-04-24 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0002_alumno_apellido_alter_alumno_edad_alter_alumno_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumno',
            name='apellido',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='alumno',
            name='direccion',
            field=models.TextField(),
        ),
    ]
