# Generated by Django 5.2 on 2025-05-07 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0003_alter_alumno_apellido_alter_alumno_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumno',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='estudiantes/', verbose_name='Foto del alumno'),
        ),
    ]
