# Generated by Django 5.2 on 2025-05-15 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0005_alumno_matricula_inscripcion_materia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='materia',
            name='codigo',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='materia',
            name='creditos',
            field=models.PositiveIntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('P1', 'Examen 1'), ('P2', 'Taller 2'), ('P3', 'Exposición 3'), ('EX', 'Examen Final'), ('TA', 'Tarea'), ('PR', 'Proyecto'), ('OT', 'Otro')], default='P1', max_length=2),
        ),
    ]
