# Generated by Django 5.2 on 2025-05-15 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0006_alter_materia_codigo_alter_materia_creditos_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='creditos',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='profesor',
        ),
    ]
