# Generated by Django 5.2 on 2025-05-15 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0007_remove_materia_codigo_remove_materia_creditos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('P1', 'Examen '), ('P2', 'Taller '), ('P3', 'Exposición '), ('EX', 'Examen Final'), ('TA', 'Tarea'), ('PR', 'Proyecto'), ('OT', 'Otro')], default='P1', max_length=2),
        ),
    ]
