# Generated by Django 5.2 on 2025-07-09 03:58

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0008_alter_nota_tipo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alumno',
            options={'ordering': ['apellido', 'nombre']},
        ),
        migrations.AlterModelOptions(
            name='inscripcion',
            options={'ordering': ['-fecha_inscripcion'], 'verbose_name_plural': 'Inscripciones'},
        ),
        migrations.AlterModelOptions(
            name='materia',
            options={'ordering': ['nombre'], 'verbose_name_plural': 'Materias'},
        ),
        migrations.AlterModelOptions(
            name='nota',
            options={'ordering': ['fecha_registro'], 'verbose_name_plural': 'Notas'},
        ),
        migrations.RemoveField(
            model_name='materia',
            name='alumnos',
        ),
        migrations.AddField(
            model_name='materia',
            name='nota_minima_aprobatoria',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(20)]),
        ),
        migrations.AlterField(
            model_name='nota',
            name='tipo',
            field=models.CharField(choices=[('P1', 'Examen'), ('P2', 'Taller'), ('P3', 'Exposición'), ('EX', 'Examen Final'), ('TA', 'Tarea'), ('PR', 'Proyecto'), ('OT', 'Otro')], default='P1', max_length=2),
        ),
        migrations.CreateModel(
            name='Periodo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(choices=[('I', 'Periodo I'), ('II', 'Periodo II'), ('III', 'Periodo III'), ('IV', 'Periodo IV')], max_length=50)),
                ('año', models.PositiveIntegerField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
            options={
                'verbose_name': 'Período',
                'verbose_name_plural': 'Períodos',
                'ordering': ['año', 'nombre'],
                'unique_together': {('nombre', 'año')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='inscripcion',
            name='periodo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='formulario.periodo'),
        ),
        migrations.AlterUniqueTogether(
            name='inscripcion',
            unique_together={('alumno', 'materia', 'periodo')},
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cedula', models.CharField(max_length=20, unique=True)),
                ('telefono', models.CharField(max_length=15)),
                ('direccion', models.TextField()),
                ('fecha_contratacion', models.DateField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='materia',
            name='profesor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='materias_impartidas', to='formulario.profesor'),
        ),
        migrations.RemoveField(
            model_name='inscripcion',
            name='ciclo_escolar',
        ),
    ]
