# Generated by Django 5.2 on 2025-07-09 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0009_alter_alumno_options_alter_inscripcion_options_and_more'),
    ]

    operations = [
    ]
