# Generated by Django 5.2 on 2025-07-10 01:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formulario', '0010_asignar_periodos_a_inscripciones'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='periodo',
            options={'ordering': ['-año', 'nombre']},
        ),
        migrations.AlterField(
            model_name='inscripcion',
            name='periodo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='formulario.periodo'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(choices=[('I', 'Periodo I'), ('II', 'Periodo II')], max_length=2),
        ),
    ]
